### ISSUE TITLE
Dependency to 'pytorch_pretrained_bert' left in train_extractive.py

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#1]
Thanks for the amazing code repo ! 😃 

In the dependencies list, you mentioned `pytorch_transformers`, so you moved to the new version of HuggingFace library.

However there is still a dependency to `pytorch_pretrained_bert` in [`train_extractive.py`](https://github.com/nlpyang/PreSumm/blob/a77e50a0793506137a257c8e8cd04b1a6a1f2d2e/src/train_extractive.py#L15).

**Comment by nlpyang** [comment]
Sorry for my neglection, this has been fixed now
