### ISSUE TITLE
Index out of range when testing on CNN Daily Mail dataset

### ISSUE THREAD

**Issue by Tanmay06** [nlpyang/PreSumm#10]
Facing index out of range error
<code>---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-91-0bfb596fe99b> in <module>
     10 
     11 predictor = build_predictor(args, tokenizer, symbols, summ)
---> 12 predictor.translate(test_iter, step)

~\Documents\Abstractive_Summarisation\PreSUMM_pytorch\src\models\predictor.py in translate(self, data_iter, step, attn_debug)
    147                     gold_tgt_len = batch.tgt.size(1)
    148                     self.min_length = gold_tgt_len + 20
--> 149                     self.max_length = gold_tgt_len + 60
    150                 batch_data = self.translate_batch(batch)
    151                 translations = self.from_batch(batch_data)

~\Documents\Abstractive_Summarisation\PreSUMM_pytorch\src\models\predictor.py in translate_batch(self, batch, fast)
    216             return self._fast_translate_batch(
    217                 batch,
--> 218                 self.max_length,
    219                 min_length = self.min_length)
    220 

~\Documents\Abstractive_Summarisation\PreSUMM_pytorch\src\models\predictor.py in _fast_translate_batch(self, batch, max_length, min_length)
    233         segs = batch.segs
    234         mask_src = batch.mask_src
--> 235 
    236         src_features = self.model.bert(src, segs, mask_src)
    237         dec_states = self.model.decoder.init_decoder_state(src, src_features, with_cache=True)

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~\Documents\Abstractive_Summarisation\PreSUMM_pytorch\src\models\model_builder.py in forward(self, x, segs, mask)
    125     def forward(self, x, segs, mask):
    126         if(self.finetune):
--> 127             top_vec, _ = self.model(x, segs, attention_mask=mask)
    128         else:
    129             self.eval()

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~\Anaconda3\envs\pytorch\lib\site-packages\pytorch_transformers\modeling_bert.py in forward(self, input_ids, token_type_ids, attention_mask, position_ids, head_mask)
    710             head_mask = [None] * self.config.num_hidden_layers
    711 
--> 712         embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids)
    713         encoder_outputs = self.encoder(embedding_output,
    714                                        extended_attention_mask,

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~\Anaconda3\envs\pytorch\lib\site-packages\pytorch_transformers\modeling_bert.py in forward(self, input_ids, token_type_ids, position_ids)
    263 
    264         words_embeddings = self.word_embeddings(input_ids)
--> 265         position_embeddings = self.position_embeddings(position_ids)
    266         token_type_embeddings = self.token_type_embeddings(token_type_ids)
    267 

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\sparse.py in forward(self, input)
    116         return F.embedding(
    117             input, self.weight, self.padding_idx, self.max_norm,
--> 118             self.norm_type, self.scale_grad_by_freq, self.sparse)
    119 
    120     def extra_repr(self):

~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1452         # remove once script supports set_grad_enabled
   1453         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1454     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1455 
   1456 

RuntimeError: index out of range at c:\n\pytorch_1559129895673\work\aten\src\th\generic/THTensorEvenMoreMath.cpp:191
</code>

**Comment by nlpyang** [comment]
please always paste your commands or I cannot see what's happening here

**Comment by Tanmay06** [comment]
Sorry, I understand that I should have given more pretext to issue that I have posted. Actually I was trying to run test on CNN Daily Mail preprocessed dataset using pretrained model, but this error popped up. Apparently I was using default arg max_pos = 800 changing it to 512 resolved the issue.

**Comment by nlpyang** [comment]
Never mind. Glad to see it was solved.
