### ISSUE TITLE
Improve README, esp for raw text input

### ISSUE THREAD

**Issue by aamin21** [nlpyang/PreSumm#129]
I apologize for the questions, but I am a bit confused on "use -mode test_text and use -text_src $RAW_SRC.TXT to input your text file." --> Use them with which file? When? Do we do this after going through Option 1/2 and then training? 

I think a nicely written step wise instruction will be immensely valuable!

**Comment by binhna** [comment]
> I apologize for the questions, but I am a bit confused on "use -mode test_text and use -text_src $RAW_SRC.TXT to input your text file." --> Use them with which file? When? Do we do this after going through Option 1/2 and then training?
> 
> I think a nicely written step wise instruction will be immensely valuable!

The `-mode test_text` and `-text_src` is for prediction. After training, you got your pretrained model, then use that model to make a new summarization from the `$RAW_SRC.TXT`. To do so, you need to assign the `mode` to `test_text` and provide the program which text file are you willing to extract the summarization in the `text_src`
