### ISSUE TITLE
is the configuration same for bert large?

### ISSUE THREAD

**Issue by rush86999** [nlpyang/PreSumm#13]
If I were to train using bert large what modifications if any should be done. For example number of decoder layers, attention heads for extractor and decoder, dec_ff_size,  enc_ff_size, enc_hidden_size, ext_hidden_size, dec_hidden_size? Can the defaults be used?

**Comment by nlpyang** [comment]
If you are doing extractive, large version is the same with base version.

I have not tried using large version for abstractive, so only experiments can tell us.
