### ISSUE TITLE
Extractive Summarization on Custom txt file not working.

### ISSUE THREAD

**Issue by kbagalo** [nlpyang/PreSumm#130]
I am trying to run the model on the test data provided in the raw_data folder (dev branch). The summary I am getting is always the 1st sentence of every record in the source file.
Is there a way to change the no of sentences in the summary, and get more sentences as a part of summary?
Tried changing in trainer_ext.py
```
trainer_ext.py
if ((not cal_oracle) and (not self.args.recall_eval) and len(_pred) == 5):
```

but it does not work. The arguments I am using are:
`-task ext -mode test_text -test_from ../models/bertext_cnndm_transformer.pt -text_src ../raw_data/temp_ext_raw_src.txt -result_path ../results/ootb_output -alpha 0.95 -log_file ../logs/test.log -visible_gpus -1`

**Comment by kbagalo** [comment]
I am trying to run the model on the test data provided in the raw_data folder (dev branch). The summary I am getting is always the 1st sentence of every record in the source file.
Is there a way to change the no of sentences in the summary, and get more sentences as a part of summary?
Tried changing 
`trainer_ext.py`
`if ((not cal_oracle) and (not self.args.recall_eval) and len(_pred) == 5):`

but it does not work.

**Comment by xnancy** [comment]
I encountered the same problem and after digging around, found the issue is in src/models/data_loader.py. In the load_text function, you need to patch _process_src so that the special tokens '[CLS]' and '[SEP]' are not tokenized by the tokenizer. As it stands, the special tokens are tokenized by BertTokenizer, so the dataloader does not recognize the delims for multiple sentences. A quick fix merging all '[', '[##cl]', '[##s]', '##]' => '[CLS]' and '[', '##se', '##p', '##]' => '[SEP]' in src_subtokens should fix your problem.

**Comment by guozhonghao1994** [comment]
Hello @xnancy ! Thank you for the answer. But I still can't solve the problem from your word. Could you please post the part where you did any change in data_loader.py? Thanks so much!

**Comment by kbagalo** [comment]
@xnancy you are right, I had found and resolved the issue sometime earlier. The problem is once the special tokens '[CLS]' and '[SEP]' are converted to lower case, they are not recognized as "special" by the tokenizer anymore, and you end up getting 1 single sentence for your entire input.  Sharing a workaround here. All you need to do is go to dataloader.py, in the function _process_src(raw), comment out the lower() (line 301) method call.
`def _process_src(raw):
        raw = raw.strip() #lower()`
You may want to add the lower at some other time in your data.

**Comment by phuawenpu** [comment]
Noob question, but where are the output summaries stored? I tried to set -result_path ../results

**Comment by phuawenpu** [comment]
Hi @kbagalo / @xnancy  and others,
this is a newbie question: I tried to run with python train.py -task ext -mode test_text -test_from ../models/bertsum_ext/model_step_148000.pt -text_src ../raw_data/temp_ext_raw_src.txt -result_path ../results -alpha 0.95 -log_file ../logs/test.log -visible_gpus 0

but I got a RuntimeError: Error(s) in loading state_dict for ExtSummarizer: .... the log is attached 
[test.log](https://github.com/nlpyang/PreSumm/files/4407937/test.log)

Any help would be appreciated! Thank you,
Wenpu.

**Comment by nlpyang** [comment]
This is indeed a bug, I have pushed a update to fix this.
Sorry for this.

**Comment by dardodel** [comment]
@nlpyang Thanks for your response. But I cannot find the update on your Github. Can you please direct us to it's location? Also, can you please make a simple sample and the code to run it in different modes, abstractive and extractive? I really appreciate it. Thanks.

**Comment by nikisix** [comment]
Anyone have the empty summary (in the gold file) problem?

**Comment by nikisix** [comment]
Was when the `-tect_tgt` parameter was blank

**Comment by nlpyang** [comment]
> @nlpyang Thanks for your response. But I cannot find the update on your Github. Can you please direct us to it's location? Also, can you please make a simple sample and the code to run it in different modes, abstractive and extractive? I really appreciate it. Thanks.

pull the repo and you will see the updates.

**Comment by nikisix** [comment]
I also found `src_subtokens = [token.replace('##.', '[SEP]') for token in src_subtokens]` helpful fwiw.

**Comment by Hellscream64** [comment]
Still getting the one-sentence-error,  Anyone else ?
