### ISSUE TITLE
Oracle and Lead3 Rouge scores on pre-processed data

### ISSUE THREAD

**Issue by kent930** [nlpyang/PreSumm#133]
Hello,

When I compute the Rouge scores for the CNN/DailyMail dataset, using the pre-processed data downloaded through this [repository](https://drive.google.com/open?id=1DN7ClZCCXsk2KegmC6t4ClBwtAf5galI) I get different results from these in the paper.
Especially for the RougeL metric. 

From the pre-processed data:
| Model   |   R1     |     R2   |RL   | 
|-----------|-----------|---------|---|
|  Oracle | 56.24 |  33.76 | 39.98 |  
|  Lead-3 | 40.14 | 17.55  | 25.07   |  

In the paper:
| Model   | R1 | R2   |RL   | 
|-----------|-----------|---|---|
|  Oracle  | 52.59 |31.24   |48.87   |  
|  Lead-3  | 40.42   | 17.62   |36.67   |  

Do you have an idea why I have such a difference?
Thank you

Edit: Just find the mistake. [Pyrouge](https://pypi.org/project/pyrouge/) requires to write summaries with one sentence per line, not all the summary on one line. 
Doing this fixes the RougeL mistmatch.

**Comment by nakhunchumpolsathien** [comment]
Hello, I would like to know what script did you use to evaluate LEAD and Oracle ROUGE score?

Thank you.

**Comment by kent930** [comment]
This is the script I use: [main.txt](https://github.com/nlpyang/PreSumm/files/4289547/main.txt)

**Comment by nakhunchumpolsathien** [comment]
@kent930 Could you please kindly share you updated script.

**Comment by kent930** [comment]
Here is the updated script: https://pastebin.com/E20G4qyc
