### ISSUE TITLE
is the comment out code for max_pos need to be uncommented?

### ISSUE THREAD

**Issue by rush86999** [nlpyang/PreSumm#14]
If the max_pos is greater than 512 then should we uncomment out this 

```
 # if(args.max_pos>512):
        #     my_pos_embeddings = nn.Embedding(args.max_pos, self.bert.model.config.hidden_size)
        #     my_pos_embeddings.weight.data[:512] = self.bert.model.embeddings.position_embeddings.weight.data
        #     my_pos_embeddings.weight.data[512:] = self.bert.model.embeddings.position_embeddings.weight.data[-1][None,:].repeat(args.max_pos-512,1)
        #     self.bert.model.embeddings.position_embeddings = my_pos_embeddings
```
and also include it in the ExtSummarizer to increase position size?

**Comment by nlpyang** [comment]
checkout dev for encoding text longer than 512 (in both preprocessing and training)

This will be integrated soon

**Comment by rush86999** [comment]
I am looking at max_pos in the dev branch and I saw the dataloader.py file as well as the above code uncommented. From looking at it, I don't see why the bert model's embeddings are not increased in the ExtSummarizer as well? If the article size is > 512 than the bert model should also have position embeddings increased and trained on, No?

**Comment by nlpyang** [comment]
Yes, this should be added to ExtSummarizer as well.

Since we did some integration of two projects when releasing this code, there might be some missing parts. We will update the codes soon.

Thanks for pointing this out.
