### ISSUE TITLE
GPU program failed to execute : cublas runtime error

### ISSUE THREAD

**Issue by AyeshaSarwar** [nlpyang/PreSumm#140]
I ran this command on my command prompt

python train.py -task ext -mode train -bert_data_path C:\Users\Ayesha\Downloads\Tasks\BERTSumm\PreSumm-dev\PreSumm-dev\bert_data\cnndm -ext_dropout 0.1 -model_path C:\Users\Ayesha\Downloads\Tasks\BERTSumm\PreSumm-dev\PreSumm-dev\models -lr 2e-3 -visible_gpus 0 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -train_steps 50 -accum_count 2 -log_file ../logs/ext_bert_cnndm -use_interval true -warmup_steps 10000 -max_pos 512

and I am getting this error

![5](https://user-images.githubusercontent.com/51691311/77826186-b4dceb00-712f-11ea-9e90-ef3b3c535909.PNG)

System Specifications
Windows 10
NVIDIA GPU RTX 2060 

How can I solve this?

**Comment by AyeshaSarwar** [comment]
I am still unable to run this code. It is giving me the same errors.

**Comment by chandanrao007** [comment]
Some pytorch dependency errors in local machine. Better to use google COLAB TPU, download the dataset using wget and gdown commands, you will not get this error.

**Comment by AanchalA** [comment]
> 
> 
> Some pytorch dependency errors in local machine. Better to use google COLAB TPU, download the dataset using wget and gdown commands, you will not get this error.

Hey I am using Colab, but I'm falling short of space in colab. What can I do?

**Comment by AanchalA** [comment]
> 
> 
> Some pytorch dependency errors in local machine. Better to use google COLAB TPU, download the dataset using wget and gdown commands, you will not get this error.


RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/torch/csrc/cuda/Module.cpp:33

This is the error I get when I try to use the COLAB TPU.

**Comment by AyeshaSarwar** [comment]
I actually was trying to run it on my PC which has Windows installed. Then, after discussing it with my colleague, I ran it on PC with Ubuntu.. It ran successfully.. Actually, it is about how both OS interacts with the GPU and loads data.. That is why it is giving such errors. I would recommend you too to run it on Ubuntu server or COLAB to get rid off such errors, if you r running it on Windows PC.

**Comment by AanchalA** [comment]
@AyeshaSarwar 
I was also getting a lot of errors when I tried running it on Windows, and so I switched to Colab. But now when I run it on Colab GPU, i.m falling short of space. I think others have also run this code on Colab, and it worked fine for them. I don't understand where am I going wrong

**Comment by AyeshaSarwar** [comment]
Oh, actually, I have a Ubuntu server so I tried running it there. COLAB is online so internet issues. Try running it on a dedicated server, may be assigned to you from your institution.

**Comment by chandanrao7** [comment]
> > Some pytorch dependency errors in local machine. Better to use google COLAB TPU, download the dataset using wget and gdown commands, you will not get this error.
> 
> RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/torch/csrc/cuda/Module.cpp:33
> 
> This is the error I get when I try to use the COLAB TPU.

When running the python file, change the parameter visible_gpu's=-1  instead of visible_gpu=0,1,2,3 and may be use colab gpu.

**Comment by NandaKishoreJoshi** [comment]
@AyeshaSarwar ,
How did you solve this issue? I'm trying to run the code on colab. with visible_gpu=0,1,2,3 I'm getting the same error. With visible_gpu=-1 and colab runtime set to GPU we do not use the GPU.

**Comment by HungVS** [comment]
> I actually was trying to run it on my PC which has Windows installed. Then, after discussing it with my colleague, I ran it on PC with Ubuntu.. It ran successfully.. Actually, it is about how both OS interacts with the GPU and loads data.. That is why it is giving such errors. I would recommend you too to run it on Ubuntu server or COLAB to get rid off such errors, if you r running it on Windows PC.

Could you share with me the specifications and requirements in your Ubuntu server? such as (Ubuntu version, Cuda version, Python dependencies,...)

I also use an Ubuntu server and still face the same error.

Thanks.
