### ISSUE TITLE
`models.optimizers` not found when loading `state_dict`

### ISSUE THREAD

**Issue by seankala** [nlpyang/PreSumm#141]
When I download the pretrained model `state_dict`s and try to load them using

```Python
model = torch.load(PATH_TO_STATEDICT)
```

I get the error:

`ModuleNotFoundError: No module named `models.optimizers``

I'm assuming that there should also be an optimizer that's used, but it hasn't been uploaded? Or am I doing something incorrectly here?

**Comment by seankala** [comment]
You have to have the `state_dict` in the `src` directory, that way it can access the `models` directory.

**Comment by MariamRiaz** [comment]
Hi can you tell me how you solved this problem
