### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '..\\logs\\cnndm.log

### ISSUE THREAD

**Issue by AanchalA** [nlpyang/PreSumm#144]
During step 3:  Sentence Splitting and Tokenization. i am getting this error

**Comment by nikisix** [comment]
supply the log argument when running the script.
Ex:
`  -log_file logs/cnndm.log`

**Comment by nikisix** [comment]
Keep in mind which directory you're running it from. The above parameter will work if you're in the top-level PreSumm directory (you may need to change the forward slash since it looks like you're on Windoze).

**Comment by AanchalA** [comment]
I ran this command as @nikisix suggested but after that i'm getting the following error

` python .\PreSumm\src\preprocess.py -mode tokenize -raw_path .\PreSumm\raw_stories\ -save_path .\PreSumm\merged_stories_tokenized\ -log_file .\PreSumm\logs\cnndm.log`


Preparing to tokenize F:\Data Science\NLP\BERT\PreSumm\raw_stories to F:\Data Science\NLP\BERT\PreSumm\merged_stories_tokenized...
Making list of files to tokenize...
Tokenizing 2 files in F:\Data Science\NLP\BERT\PreSumm\raw_stories and saving in F:\Data Science\NLP\BERT\PreSumm\merged_stories_tokenized...
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
Stanford CoreNLP Tokenizer has finished.
Traceback (most recent call last):
  File ".\PreSumm\src\preprocess.py", line 73, in <module>
    eval('data_builder.'+args.mode + '(args)')
  File "<string>", line 1, in <module>
  File "F:\Data Science\NLP\BERT\PreSumm\src\prepro\data_builder.py", line 137, in tokenize
    tokenized_stories_dir, num_tokenized, stories_dir, num_orig))
Exception: The tokenized stories directory F:\Data Science\NLP\BERT\PreSumm\merged_stories_tokenized contains 0 files, but it should contain the same number as F:\Data Science\NLP\BERT\PreSumm\raw_stories (which has 
2 files). Was there an error during tokenization?

**Comment by nikisix** [comment]
@AanchalA `Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP`
This error means the standford nlp java module wasn't recognized via the CLASSPATH environmental variable. Make sure that's set properly according to the instructions in Step 2

**Comment by AanchalA** [comment]
I guess I have followed the steps correctly. I downloaded Stanford CoreNLP 3.9.2.zip, extracted it and saved it in the PreSumm folder, then I created a .batch_profile and added the following line in the file 

`export CLASSPATH=/F:/Data Science/NLP/BERT/PreSumm/stanford-corenlp-full-2018-10-05/stanford-corenlp-3.9.2.jar`

**Comment by nikisix** [comment]
@AanchalA 
Is it batch_profile on windows or bash_profile as in *nix?
Did you remember to source your bash_profile?
You can also run that on the command line to set the variable explicitly for the current session.

After you fix this step, I had a problem with the next one (don't recall the exact error) so have taken to running the stanford jar directly via:
```
java edu.stanford.nlp.pipeline.StanfordCoreNLP \
  -annotators tokenize,ssplit \
  -ssplit.newlineIsSentenceBreak always \
  -filelist mapping_for_corenlp.txt \
  -outputFormat json \
  -outputDirectory ./results
```

One needs to add the filepaths (one per line) into the mapping_for_corenlp.txt file.

Good luck!

**Comment by AanchalA** [comment]
@nikisix 
Hey, I'm confused about which filepaths am I supposed to add to mapping_for_corenlp.txt file?

**Comment by nikisix** [comment]
The source text files you'd like to tokenize

**Comment by azraar** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '..\\logs\\cnndm.log 

i have sampe issue please @AanchalA help me

**Comment by AanchalA** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '..\logs\cnndm.log
> 
> i have sampe issue please @AanchalA help me

You just have to create a folder named logs. That will solve the issue

**Comment by azraar** [comment]
thank you so much @AanchalA 
SORRY I HAVE ANOTHER ERROR IF YOU CAN HELP ME 

FileNotFoundError: [Errno 2] No such file or directory: 'BERT_DATA_PATH.train.pt'

i create file name BERT_DATA_PATH ../bert_data/cnndm 
but still the error is showing

**Comment by AanchalA** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '..\logs\cnndm.log
> 
> i have sampe issue please @AanchalA help me

You just have to create a folder named logs. That will solve the issue

> thank you so much @AanchalA
> SORRY I HAVE ANOTHER ERROR IF YOU CAN HELP ME
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'BERT_DATA_PATH.train.pt'
> 
> i create file name BERT_DATA_PATH ../bert_data/cnndm
> but still the error is showing

Can you show the entire error. And where did you create `BERT_DATA_PATH`?

**Comment by azraar** [comment]
![Capture](https://user-images.githubusercontent.com/50860620/94050790-51472800-fe09-11ea-9980-b3359d1e298d.JPG)

**Comment by zihanxu3** [comment]
@azraar were you able to figure out the BERT_DATA_PATH error? Thanks!

**Comment by kush-2418** [comment]
> @AanchalA `Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP` This error means the standford nlp java module wasn't recognized via the CLASSPATH environmental variable. Make sure that's set properly according to the instructions in Step 2

Add to databuilder.py

   command = ['java','-cp', '/path/stanford-corenlp-4.4.0/*','edu.stanford.nlp.pipeline.StanfordCoreNLP', '-annotators', 'tokenize,ssplit',
               '-ssplit.newlineIsSentenceBreak', 'always', '-filelist', 'mapping_for_corenlp.txt', '-outputFormat',
               'json', '-outputDirectory', tokenized_stories_dir]
