### ISSUE TITLE
Running as suggested in the README doesn't work and causes cascade of errors.

### ISSUE THREAD

**Issue by seankala** [nlpyang/PreSumm#148]
Sorry about the rather broad title. I can't be the only one who's facing this issue, but when I try to run the code as specified on the README file, I face errors.

# Error 1
The first error is that there's no module named `pytorch_transformers`. No big deal, I just change the name to `transformers` as the Hugging Face implementations also changed their name recently.

# Error 2
The second error is that I get a `FileNotFoundError: [Errno 2] No such file or directory: '../bert_data/.train.pt'`. This seems like a bit of a strange error to me. Shouldn't the correct path be specified in the code? I don't think I should need to manually change the path if I copy and pasted the `.pt` files into the `bert_data/` directory as specified in the README file. Perhaps I'm misinformed and someone can help me out with this.

The particular code that causes this error is line 85 of the `data_loader.py` module:

```Python
# Change this:
pts = sorted(glob.glob(args.bert_data_path + '.' + corpus_type + '[0-9]*.pt'))

# to this:
pts = sorted(glob.glob(args.bert_data_path + 'cnndm' + '.' + corpus_type + '.[0-9]*.pt'))
```

Again, maybe I'm not understanding how this code is supposed to run properly, but it just seemed like a really strange error and I'm curious as to how the model was intended to run in the first place with that code.

# Error 3
After fixing this, you get the error that:

```Python
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

No worries, just find the `1 - (something)` and change it to `~(something)`.

# Error 4
This is the error that I'm having trouble fixing, and I opened a Git Issue here which hasn't been address yet.

```Python
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train_abs(args, device_id)
  File "/home/user1/PreSumm/src/train_abstractive.py", line 273, in train_abs
    train_abs_single(args, device_id)
  File "/home/user1/PreSumm/src/train_abstractive.py", line 334, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/home/user1/PreSumm/src/models/trainer.py", line 158, in train
    report_stats)
  File "/home/user1/PreSumm/src/models/trainer.py", line 223, in _gradient_accumulation
    outputs, scores = self.model(src, tgt,segs, clss, mask_src, mask_tgt, mask_cls)
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user1/PreSumm/src/models/model_builder.py", line 241, in forward
    top_vec = self.bert(src, segs, mask_src)
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user1/PreSumm/src/models/model_builder.py", line 127, in forward
    top_vec, _ = self.model(x, segs, attention_mask=mask)
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got multiple values for argument 'attention_mask'
```

I don't expect an outright solution to this issue, and I probably need to get more acquainted with the Hugging Face interface anyway, but I'm just curious as to why this error is occurring and if someone who's more knowledge than myself could help me out.

Sorry for the long post, just wanted to make some suggestions on revising the code.

**Comment by onrmrt** [comment]
**Error 1:** PyTorch-Transformers package is still active. I recommend using it for compatibility reasons.
https://pypi.org/project/pytorch-transformers/

**Error 2:** If you specify bert_data_path as bert_data/cnndm without changing the code, you can fix this problem.

**Error 3:** Pytorch 1.1.0 was used in the project. The error you received indicates that you are not using this version. I think you will get rid of many problems if you use version 1.1.0.

**Error 4:** I think the problem stems from the use of the transformers package instead of pytorch-transformers.

**Comment by seankala** [comment]
Thanks for the comment, I hadn't realized that PyTorch Transformers was still active. I downloaded it using `pip install pytorch_transformers`.

The other issues also worked as you suggested. I just think it's a bit weird that the README file isn't a little more explicit regarding the details for execution. Thanks!
