### ISSUE TITLE
The test_text mode is not a valid value for argument parser -mode in train.py

### ISSUE THREAD

**Issue by exoushia** [nlpyang/PreSumm#156]
For using a raw txt file, the argument parsers, which the Readme mentions to be used, aren't defined in train.py for it to run. For example -text_src and -test_from (only -bert_data_path is available). This is after I added "test_text" as a valid value for the arg parser "-mode". 
![image](https://user-images.githubusercontent.com/45519518/80493189-b4c84900-8982-11ea-82a9-35cd14008295.png)

Kindly help me out here, I'll be very thankful.

**Comment by darsh10** [comment]
Hi,

Did you find a solution ? I did the same thing. Added test_text as a valid value for -mode

**Comment by exoushia** [comment]
Hello,
Yeah I was cloned the master branch instead of dev and hence was a fault on
my part. I did close the issue though.
