### ISSUE TITLE
(OSX) Torch not compiled with CUDA enabled 

### ISSUE THREAD

**Issue by STEMlib** [nlpyang/PreSumm#159]
Receiving assertion error below. 
`AssertionError: Torch not compiled with CUDA enabled`
Check links [pytorch issue 30664](https://github.com/pytorch/pytorch/issues/30664), which seems focused on PC. Is there work around for Mac where CUDA-capable GPUs aren't available?

**Comment by ahmad88me** [comment]
on mac, you can use 
`device = "mps"` instead of `device="cuda"`.
