### ISSUE TITLE
XSum model's performance (ROUGE scores)

### ISSUE THREAD

**Issue by 6desislava6** [nlpyang/PreSumm#171]
Hello!
First, thank you for the wonderful paper and the provided code, models, data, outputs & results.
I was wondering whether the model in the README for the XSum dataset - [XSum BertExtAbs](https://drive.google.com/open?id=1H50fClyTkNprWJNh10HWdGEdDdQIkzsI) - is indeed the best performing model. It appears to has been trained only for 30k steps on the abstractive task and these are the results I got for ROUGE:
`ROUGE-F(1/2/3/l): 33.16/12.96/25.12` instead of the ones in the paper: `38.81 16.50 31.27`.

Many thanks in advance!

**Comment by 6desislava6** [comment]
I think I got the min_length and max_length params wrong. My bad, cheers.
PS: yup, that was the case.

**Comment by Shashi456** [comment]
@6desislava6 did you decode 2 sentences or 3?

**Comment by gaozhiguang** [comment]
Hi, how do you set the max_length and min_length?
