### ISSUE TITLE
Problem with Step5. Get 2 empty brackets after running format-to-bert

### ISSUE THREAD

**Issue by DarlineFiedler** [nlpyang/PreSumm#180]
I got a problem. When I do step four, I get this as an answer: 

```
(base) D:\Studium\Bachelor Arbeit\Bachlorarbeit\Bachelorarbeit\BERT\BertSum\PreSumm\src>python preprocess.py -mode format_to_bert -raw_path ../json_data -save_path ../bert_data  -lower -n_cpus 1 -log_file ../logs/preprocess.log
[('train', '../json_data\\cnndm_sample.train.0.json', Namespace(dataset='', log_file='../logs/preprocess.log', lower=True, map_path='../../data/', max_src_nsents=100, max_src_ntokens_per_sent=200, max_tgt_ntokens=500, min_src_nsents=3, min_src_ntokens_per_sent=5, min_tgt_ntokens=5, mode='format_to_bert', n_cpus=1, pretrained_model='bert', raw_path='../json_data', save_path='../bert_data', select_mode='greedy', shard_size=2000, use_bert_basic_tokenizer=False), '../bert_data\\bert.pt_data\\cnndm_sample.train.0.bert.pt')]
[]
[]
```

The command I execute is this: 

`python preprocess.py -mode format_to_bert -raw_path ../json_data -save_path ../bert_data  -lower -n_cpus 1 -log_file ../logs/preprocess.log`

Are the empty brackets bad?

**Comment by SebastianVeile** [comment]
Empty brackets just mean it can't find anything in the directory you have put. It might have to do with you using windows and the way windows handles paths. I do not use windows myself and cannot help you with the paths, but this part `'../json_data\\cnndm_sample.train.0.json'` doesn't look right to me.

**Comment by DarlineFiedler** [comment]
I actually just forgot to create the valid and test data. Now everything's going great.
