### ISSUE TITLE
Issue in greedy selection

### ISSUE THREAD

**Issue by pulkit25** [nlpyang/PreSumm#182]
https://github.com/nlpyang/PreSumm/blob/70b810e0f06d179022958dd35c1a3385fe87f28c/src/prepro/data_builder.py#L176

Hi, I noticed this line of code which did not make sense to me as we are assigning the cur_max_rouge to max_rouge and then reassigning it at the start of the loop. Is there a mistake here?

**Comment by JanMarcelKezmann** [comment]
From my point of view the code line you have mentioned is correct, but at the end of the loop there is definitively a mistake, when *cur_max_rouge* is reinitialized to *max_rouge*.
From my point of view it should be changed to:

`cur_max_rouge = 0.0`
