### ISSUE TITLE
Can this model handle long document?

### ISSUE THREAD

**Issue by chz816** [nlpyang/PreSumm#183]
Hi! Thank you for contributing this amazing paper. I am wondering if this model can handle the very-long document?

**Comment by SebastianVeile** [comment]
I believe the maximum bert sequence length is 512. Therefore longer source documents are truncated.

**Comment by chz816** [comment]
> I believe the maximum bert sequence length is 512. Therefore longer source documents are truncated.

That's what I thought. Thank you!

**Comment by SebastianVeile** [comment]
There may actually be a way for you to increase the document length by using the specific parameter -max _pos "number". Currently in the code, it is set to the standard of 512, but can be increased.

**Comment by AyeshaSarwar** [comment]
@SebastianVeile Hi. 
I want to ask @nlpyang said here for this issue https://github.com/nlpyang/PreSumm/issues/97 or in the updates section that keep max-pos to any number in the preprocessing and training.
But I cannot find max-pos parameter in the preprocessing file.
Can you kindly help me in this regard?
Should I change 512 everywhere to my desired number? Is this what they mean?
Help much appreciated.

**Comment by AyeshaSarwar** [comment]
Any help will be much appreciated.
Thanks

**Comment by AyeshaSarwar** [comment]
> There may actually be a way for you to increase the document length by using the specific parameter -max _pos "number". Currently in the code, it is set to the standard of 512, but can be increased.

So, lets say I want to consider documents with 2500 words, I can set max-pos to 2500?

@SebastianVeile

Any help will be much appreciated.
Thanks
