### ISSUE TITLE
Preprocess another dataset

### ISSUE THREAD

**Issue by matt9704** [nlpyang/PreSumm#186]
Hi! I want to implement your model on another dataset. But in this dataset, each article has one-sentence summary, which is different from CNN/Dailymail dataset (each with three-sentence summary). Can I follow the preprocess steps for CNN/Dailymail to prepocess my dataset?

**Comment by SebastianVeile** [comment]
They are selecting only one of those summaries anyways using a greedy algorithm during preprocessing. So if you only have one summary it will just select that one

**Comment by matt9704** [comment]
> They are selecting only one of those summaries anyways using a greedy algorithm during preprocessing. So if you only have one summary it will just select that one

Umm. I think they combine three sentences as one summary for an article, not just choosing one of those sentences as a summary.
For example, this is an article in CNN/Dailymail dataset. There are three highlights below the article text and the concatenation of them is the summary.
![image](https://user-images.githubusercontent.com/62277482/86487599-766e5200-bd56-11ea-8ff5-e4233c7744ac.png)

**Comment by SebastianVeile** [comment]
Ah, you are correct. That is my bad. However, I believe you have the answer to your question then. Only sentences after "@highlight " will be considered for the tgt and if you only have 1 "@highlight" it will use only that sentence, hence it will be possible to preprocess all your data to only contain 1 highlight

**Comment by matt9704** [comment]
> Ah, you are correct. That is my bad. However, I believe you have the answer to your question then. Only sentences after "@highlight " will be considered for the tgt and if you only have 1 "@highlight" it will use only that sentence, hence it will be possible to preprocess all your data to only contain 1 highlight

Maybe it'll work. I'll have a try. Thanks!
