### ISSUE TITLE
PyTorch 1.2.0 compatibility issues

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#2]
The current code is not compatible with PyTorch version 1.2.0 :

> File "[...]/PreSumm/src/models/data_loader.py", line 33, in __init__
    mask_src = 1 - (src == 0)
  File "[...]/presum/lib/python3.6/site-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
**RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.**

This masking issue is discussed [here](https://github.com/OpenNMT/OpenNMT-py/issues/1524).

_I simply went back to PyTorch 1.1.0, but maybe there is other compatibility issues ?_

---

You might want to specify the version of PyTorch in the README :)

**Comment by nlpyang** [comment]
Thanks for pointing this out. Readme has been updated.

I think the bool type in torch 1.2.0 will cause problems in masking.

For now, I would suggest to use 1.1.0

**Comment by tobystic** [comment]
I think this worked for me:

replace
>align.masked_fill_(1 - mask, -float('inf'))

with

>align.masked_fill_(~mask, -float('inf'))

**Comment by sajastu** [comment]
Changing `mask_src = 1 - (src == 0)` to `mask_src = ~(src == 0)` would help getting this around!
