### ISSUE TITLE
How to run this project if I have downloaded your pre-processed data?

### ISSUE THREAD

**Issue by Adityaa64** [nlpyang/PreSumm#21]
python train.py -task ext -mode train -bert_data_path BERT_DATA_PATH -ext_dropout 0.1 -model_path MODEL_PATH -lr 2e-3 -visible_gpus 0,1,2 -report_every 50 -save_checkpoint_steps 1000 -batch_size 3000 -train_steps 50000 -accum_count 2 -log_file ../logs/ext_bert_cnndm -use_interval true -warmup_steps 10000 -max_pos 512
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from train_abstractive import validate_abs, train_abs, baseline, test_abs, test_text_abs
  File "/home/aditya64/text summerizer/PreSumm-master/src/train_abstractive.py", line 15, in <module>
    from pytorch_transformers import BertTokenizer
ModuleNotFoundError: No module named 'pytorch_transformers'

**Comment by Colanim** [comment]
`pip install pytorch_transformers`

Check the dependencies in the README and install it.
