### ISSUE TITLE
Misunderstanding the rouge score

### ISSUE THREAD

**Issue by ghost** [nlpyang/PreSumm#222]
![image](https://user-images.githubusercontent.com/24579703/128204598-b3e1a962-afbd-4ed9-a791-564f6144fab0.png)

Not sure to understand those results. Can you explain a bit more the results? Normally, I get one Rouge-1, one Rouge-2 and one Rouge-L, but here I got three for each.

**Comment by WSChange** [comment]
How did you solve this problem? Please give me some suggestion.
