### ISSUE TITLE
Preprocessing txt files to JSON

### ISSUE THREAD

**Issue by limorigu** [nlpyang/PreSumm#24]
Thank you @nlpyang for the excellent work!

-------------------------------------------------------------------------------------------------
The following can probably be avoided if you alter the ~/.bashrc file as advised in https://stanfordnlp.github.io/CoreNLP/download.html (see step 4, second part). But I just wanted to leave it here in case it's helpful for others.
-------------------------------------------------------------------------------------------------

This might be a comment helpful to others trying to use this pipeline for the processing of other texts who are not already familiar with CoreNLP. 

If you follow the README.dm and get to option 2 of preprocessing, step 3, where the aim is to create tokenized JSONs based on the input txt (i.e. Sentence Splitting and Tokenization), you will be calling the preprocess.py file, which in turn will call prepro/data_builder.py, from which Standford CoreNLP java code will be called. I only got it to work after moving the unzipped files I downloaded from Stanford CoreNLP into my PreSumm/src folder (where I'm calling the bash command in the README from), and also changed the following line from data_builder.py:

` command = ['java', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-annotators', 'tokenize,ssplit',
               '-ssplit.newlineIsSentenceBreak', 'always', '-filelist', 'mapping_for_corenlp.txt', '-outputFormat',
               'json', '-outputDirectory', tokenized_stories_dir]
`
to: 
   ` command = ['java', '-cp', '*', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-annotators', 'tokenize,ssplit',
               '-ssplit.newlineIsSentenceBreak', 'always', '-filelist', 'mapping_for_corenlp.txt', '-outputFormat',
               'json', '-outputDirectory', tokenized_stories_dir]
`

I would be happy if a) anyone who did it differently could share their solution, b) if you are stuck on the same problem, maybe my hack would help you, c) @nlpyang, perhaps consider adding this little comment to the README file, or a comment advising to do otherwise. 

Thanks again!

**Comment by cece00** [comment]
Hi, I think it's an error of path reference. Besides the solution of moving unzipped files of Stanford CoreNLP into PreSumm/src folder, I also solved it by adding paths by export.  As the official stanfoldnlp documentation:
```
cd stanford-corenlp-4.4.0
for file in `find . -name "*.jar"`; do export CLASSPATH="$CLASSPATH:`realpath $file`"; done
```
Hope it helps. Thanks.
