### ISSUE TITLE
issue for converting to bert_data

### ISSUE THREAD

**Issue by connie-n** [nlpyang/PreSumm#240]
I tried to json data to bert data(data preprocessing step 5) but it returned empty file.. 
could anyone help me? 

I run this code with both cnndm and my own data. cnndm data was converted to bert data successfully but my own data wasn't. 
I adjusted the min_src_tokens/min_tgt_tokens but it is still not working. 

![제목 없음](https://user-images.githubusercontent.com/66296523/176628050-925004d3-ba3a-4dbd-9479-8486da297d83.png)

**Comment by kush-2418** [comment]
in data_builder.py file and in format_to_bert function do this -

for json_f in glob.glob(pjoin(args.raw_path, '.' + corpus_type + '.[0-9]*.json')):

**Comment by yassminSaber** [comment]
@connie-n  how did you solve this problem ?
