### ISSUE TITLE
❓ Question about predictions cleaning : Why replace '+' ?

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#27]
I have a question about the post-processing of model's prediction.

At this line :

https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/models/predictor.py#L154

I understand you clean the prediction to match the gold text better (for ROUGE score) :

* You remove the `beginning of sentence` / `end_of_sentence` tokens
* You replace the `sentence_separator` token with `<q>` (because it's the sentence separator used in the gold text)

But I don't understand this one :

``` python
.replace(r' +', ' ')
```

---

**Why do you need to replace + sign ? BERT tokenizer does not add any + sign during tokenization, so if it appear it must be part of the text.**

**Comment by nlpyang** [comment]
this is a regular expression
