### ISSUE TITLE
Did you run the Transformer baseline using this code?

### ISSUE THREAD

**Issue by zdou0830** [nlpyang/PreSumm#30]
Thanks for the code! Did you run the Transformer baseline using this code?

**Comment by nlpyang** [comment]
Yes, set -encoder baseline will do this.

**Comment by zdou0830** [comment]
Thanks!

**Comment by zide05** [comment]
> Thanks!

Have you reproduced the result of ABS baseline ?

**Comment by zdou0830** [comment]
> > Thanks!
> 
> Have you reproduced the result of ABS baseline ?

I reproduced the result of the EXT baseline but did not try ABS.

**Comment by zide05** [comment]
I tried ABS, but can't repreduce the result in paper.

**Comment by zide05** [comment]
> Thanks!
> 
> Have you reproduced the result of ABS baseline ?
> 
> I reproduced the result of the EXT baseline but did not try ABS.

I tried ABS, but can't repreduce the result in paper.
