### ISSUE TITLE
Increase the summary length, or number of sentences

### ISSUE THREAD

**Issue by d1sharma** [nlpyang/PreSumm#31]
Hello!
 
How can I tune this model to generate more sentences of summary? Right now it has an average of 3 sentences for ext model. I would like to have 2 more or 5 more sentences...

Thank you very much for your time!

All the best.

**Comment by eridgd** [comment]
Change `len(_pred) == 3` to the max # of sentences you'd like.  https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/models/trainer_ext.py#L275

**Comment by d1sharma** [comment]
Thank you!

**Comment by niless** [comment]
You could also produce shorter version of the summaries (1 and 2 sentences) from the 3 sentence default output without re-running `len(_pred) == n` with different n values since the sentences in the summary are ranked.
