### ISSUE TITLE
Restart training from an existing checkpoint

### ISSUE THREAD

**Issue by vnik18** [nlpyang/PreSumm#34]
Hi, thanks for sharing your code! Since the training takes a very long time, I am wondering if it is possible to stop the training at a particular checkpoint, save the checkpoint, and then restart the training after loading that same saved checkpoint. If yes, can you please let me know how it can be done? Thanks a lot!

**Comment by Colanim** [comment]
There is an option for this :

https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/train.py#L107

Just specify the checkpoint to use : `-train_from ../models/model_step_30000.pt` for example

**Comment by vnik18** [comment]
> There is an option for this :
> 
> https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/train.py#L107
> 
> Just specify the checkpoint to use : `-train_from ../models/model_step_30000.pt` for example

Thank you!

**Comment by connie-n** [comment]
Hi, I tried it but faced keyerror below. 
I fixed the code  optim = checkpoint['optim'][0] -> optim = checkpoint['optim']
but it still is not working. how can i resolve?  

File "/content/drive/MyDrive/Colab/github/PreSumm/src/models/model_builder.py", line 16, in build_optim
    optim = checkpoint['optim']
KeyError: 'optim'
