### ISSUE TITLE
Training step issue

### ISSUE THREAD

**Issue by wagu0809** [nlpyang/PreSumm#36]
Hi there, here I found that the `step += 1` is under the `for` loop of `train_iter`.
And in this case, only the first 100 samples of the first batch are used to train, is that correct?

**Comment by nlpyang** [comment]
I am not sure why do you think like that.

**Comment by nlpyang** [comment]
training_step is the total number of steps for training.

**Comment by wagu0809** [comment]
Clear now, thanks for your explanation!
