### ISSUE TITLE
Error while using model for inference :  RuntimeError: expected device cpu and dtype Byte but got device cpu and dtype Bool

### ISSUE THREAD

**Issue by ranjeetds** [nlpyang/PreSumm#37]
I am using the abstractive model for inference using following command

`python3 train.py -task abs -mode validate -batch_size 3000 -test_batch_size 500 -bert_data_path ../bert_data/cnndm -log_file ../logs/val_abs_bert_cnndm -model_path ../../model/ -sep_optim true -use_interval true -visible_gpus -1 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path ../logs/abs_bert_cnndm`

I am getting below error.

File "train.py", line 124, in <module>
    validate_abs(args, device_id)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/train_abstractive.py", line 154, in validate_abs
    validate(args, device_id, cp, step)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/train_abstractive.py", line 196, in validate
    stats = trainer.validate(valid_iter, step)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/models/trainer.py", line 197, in validate
    outputs, _ = self.model(src, tgt, segs, clss, mask_src, mask_tgt, mask_cls)
  File "/home/exa00117/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/models/model_builder.py", line 243, in forward
    decoder_outputs, state = self.decoder(tgt[:, :-1], top_vec, dec_state)
  File "/home/exa00117/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/models/decoder.py", line 202, in forward
    step=step)
  File "/home/exa00117/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/exa00117/Practice/textSummerization/presumm/PreSumm-master/src/models/decoder.py", line 64, in forward
    dec_mask = torch.gt(tgt_pad_mask + self.mask[:, :tgt_pad_mask.size(1), :tgt_pad_mask.size(1)], torch.tensor(0))
RuntimeError: expected device cpu and dtype Byte but got device cpu and dtype Bool

**Comment by ranjeetds** [comment]
Also if I print tgt_pad_mask, It has all boolean entries

`        [[False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         ...,
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True]],

        [[False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         ...,
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True]],

        ...,

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]])
`

**Comment by Satan012** [comment]
> Also if I print tgt_pad_mask, It has all boolean entries
> `
> [[False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> ...,
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True]],
> 
> ```
>     [[False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      ...,
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True]],
> 
>     ...,
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]],
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]],
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]]])
> ```
> 
> `



> Also if I print tgt_pad_mask, It has all boolean entries
> `
> [[False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> ...,
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True],
> [False, False, False, ..., True, True, True]],
> 
> ```
>     [[False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      ...,
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True],
>      [False, False, False,  ...,  True,  True,  True]],
> 
>     ...,
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]],
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]],
> 
>     [[False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      ...,
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False],
>      [False, False, False,  ..., False, False, False]]])
> ```
> 
> `

i also met this error, and i found that it caused by type mismatch.
    type --> tgt_pad_mask: boolean
    type --> self.mask: uint8
So, when you use torch.gt, error will happen. My solution is as follow, convert all into int, and 
 then you can use torch.gt:

dec_mask = torch.gt(tgt_pad_mask.int() + self.mask[:, :tgt_pad_mask.size(1),
                            :tgt_pad_mask.size(1)].int(), 0)

**Comment by ranjeetds** [comment]
Thanks @Satan012 this resolves the issue. Though I am wondering why there is a type mismatch?

**Comment by nlpyang** [comment]
please make sure you are using pytorch 1.1.0

higher version pytorch changed the way of using masks.

**Comment by ranjeetds** [comment]
Okay @nlpyang. Thanks for the clarification. I am using pytorch version 1.2.0.
