### ISSUE TITLE
❓ Question : Why ROUGE-2 for oracle sentences ?

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#4]
In your (amazing) paper, it is said that oracle sentences are made using ROUGE-2 :

![Annotation 2019-08-26 094417](https://user-images.githubusercontent.com/43774355/63658524-31000080-c7e6-11e9-9358-c2b05b92a443.png)

But in the code, it seems you match oracle sentences by using both ROUGE-1 and ROUGE-2 (similar to BertSum) :

https://github.com/nlpyang/PreSumm/blob/d5954c9890da487a40617ca77c75b02feff0d2eb/src/prepro/data_builder.py#L188

---

**Is it a typo in the paper ?**

**Comment by nlpyang** [comment]
We have tried both settings, and there is no significant difference.
