### ISSUE TITLE
In BERT Extractive Setting, what does 'xent' mean?? How to evaluate ext mode?

### ISSUE THREAD

**Issue by jdh3577** [nlpyang/PreSumm#41]
In case of BERT extractive model(BERTExt), how do I evaluate the training accuracy?? xent???
`Step 500/100000; xent: 0.46; lr: 0.0000010; 107 docs/s;   1001 sec`
I don't know what 'xent' meaning.. please let me know

**Comment by nlpyang** [comment]
xent is cross entropy loss
