### ISSUE TITLE
evaluate and test

### ISSUE THREAD

**Issue by antonysama** [nlpyang/PreSumm#45]
Downloaded, then processed and trained 'cnndm_sample.train.0.json' (documented here: https://github.com/antonysama/PreSumm/blob/master/README.md). However Evaluate and Test, steps give the following errors:
 
###Evaluate code: 
`python PreSumm/src/train.py -task abs -mode validate -test_all -batch_size 8 -test_batch_size 2 -bert_data_path ~/o3/PreSumm/bert_data/ -log_file ~/o3/PreSumm/logs/val_abs_bert_cnndm -model_path ~/o3/PreSumm/models -sep_optim true -use_interval true -visible_gpus -1 -max_pos 512 -max_length 10 -alpha 0.95 -min_length 5 -result_path ~/o3/PreSumm/logs/abs_bert_cnndm`

##Evaluate Error:
`loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at ../temp/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
Traceback (most recent call last):
  File "PreSumm/src/train.py", line 124, in <module>
    validate_abs(args, device_id)
  File "/home/antony/o3/PreSumm/src/train_abstractive.py", line 131, in validate_abs
    xent = validate(args, device_id, cp, step)
  File "/home/antony/o3/PreSumm/src/train_abstractive.py", line 187, in validate
    shuffle=False, is_test=False)
  File "/home/antony/o3/PreSumm/src/models/data_loader.py", line 136, in __init__
    self.cur_iter = self._next_dataset_iterator(datasets)
  File "/home/antony/o3/PreSumm/src/models/data_loader.py", line 156, in _next_dataset_iterator
    self.cur_dataset = next(dataset_iter)
  File "/home/antony/o3/PreSumm/src/models/data_loader.py", line 94, in load_dataset
    yield _lazy_dataset_loader(pt, corpus_type)
  File "/home/antony/o3/PreSumm/src/models/data_loader.py", line 78, in _lazy_dataset_loader
    dataset = torch.load(pt_file)
  File "/home/antony/.local/lib/python3.6/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/antony/o3/PreSumm/bert_data/.valid.pt'`

 ##Test code:
`python PreSumm/src/train.py -task abs -mode test -test_from ~/o3/PreSumm/bert_data/model_step_148000.pt -batch_size 16 -test_batch_size 2 -bert_data_path ~/o3/PreSumm/bert_data/ -log_file ~/o3/PreSumm/logs/val_abs_bert_cnndm -sep_optim true -use_interval true -visible_gpus -1 -max_pos 512 -max_length 10 -alpha 0.95 -min_length 5 -result_path ~/o3/PreSumm/logs/abs_bert_cnndm`

##Test error:
Similar to 'Evaluate' error above, but ends with 'File not found...test.pt'

**Comment by eridgd** [comment]
Change  `-bert_data_path ~/o3/PreSumm/bert_data/` to ` -bert_data_path ~/o3/PreSumm/bert_data/cnndm`, it will append the .valid/test.pt to that.

**Comment by antonysama** [comment]
@eridgd,

Thanks. The pre- processing steps change the json file 'cnndm_sample.train.0.bert.json' to  bert file, 'cnndm_sample.train.0.bert.pt' . The bert file remains with that name throughout the training steps (ex, ab & exab). It doesn't change to  'cnndm', like you show. But I tried attaching it nonetheless, to no avail. (all steps are documented: documented here: https://github.com/antonysama/PreSumm/blob/master/README.md).

**Comment by Colanim** [comment]
@antonysama 

He meant in your evaluation command, you should replace `-bert_data_path ~/o3/PreSumm/bert_data/` into `-bert_data_path ~/o3/PreSumm/bert_data/cnndm`

**Comment by antonysama** [comment]
@eridgd, @colanim,

How do you get the 'cnndm' file? Because I get  'cnndm_sample.train.0.bert.pt'  after preprocessing, and even after training. I'm missing something between the processing and training, and that's the cnndm file you mention.

**Comment by Colanim** [comment]
@antonysama 
There is no `cnndm` file

Specifying `-bert_data_path ~/o3/PreSumm/bert_data/cnndm` is just a way to indicate to the code the folder **with** the root name of your training files. So if you have data from another dataset, you can put it in the same folder with a different root name.

Just try to run the same command with this option, without changing anything else.

---

_Note : If you data files start with `cnndm_sample`, you might need to change the option to `-bert_data_path ~/o3/PreSumm/bert_data/cnndm_sample`_

**Comment by antonysama** [comment]
Thanks, I'll try this. Much appreciated.
