### ISSUE TITLE
Regarding Decoding Phase

### ISSUE THREAD

**Issue by tahmedge** [nlpyang/PreSumm#49]
I am confused regarding the decoding phase. Suppose S1, S2, S3 are three sentences and each sentence has tokens t1, t2,...... tn. (n denotes total number of tokens in the sentence).

What I understand is that at the end of the encoding phase, we will have tokens -? [CLS] [S1, T1][S1 T,2].... [SEP] [CLS] [S2 ,T1] [S2 T,2].... [SEP] [CLS] [S3 ,T1] [S3 .T2].... [SEP] .....

So during decoding the phase, is not the decoder focusing on all the tokens including [CLS] [Si, Tj] [SEP] etc. ? Or is it just focusing on [CLS] token of each sentence? I did not find detailed explanation regarding decoding phase in the paper.

**Comment by Colanim** [comment]
In the forward pass of Abstractive model :

https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/models/model_builder.py#L240-L244

Decoder uses all tokens representations from encoder, not only `[CLS]` token.

---

In the forward pass of Extractive model :

https://github.com/nlpyang/PreSumm/blob/29a6b1ace2290808f39c76ae2ef0e92d515fc049/src/models/model_builder.py#L170-L175

Extractive layers uses only `[CLS]` token representations from encoder.

**Comment by tahmedge** [comment]
Thanks for your reply. :)
