### ISSUE TITLE
Abstractor validation : ValueError (too many values to unpack)

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#5]
I ran the Abstractor validation with following command :

```
python train.py -task abs 
-mode validate 
-batch_size 3000 
-test_batch_size 500 
-bert_data_path ~/PreSumm/bert_data/cnndm 
-log_file ../logs/val_abs_bert_cnndm 
-model_path ../models/BertSumExtAbs 
-sep_optim true 
-use_interval true 
-visible_gpus 1 
-max_pos 512 
-max_length 200 
-alpha 0.95 
-min_length 50 
-result_path ../logs/abs_bert_cnndm 
-test_all
```

But at test time (after evaluating every checkpoints on `valid` dataset), I got this error :

> Traceback (most recent call last):
  File "train.py", line 124, in <module>
    validate_abs(args, device_id)
  File "[...]/PreSumm/src/train_abstractive.py", line 140, in validate_abs
    test_abs(args, device_id, cp, step)
  File "[...]/PreSumm/src/train_abstractive.py", line 225, in test_abs
    predictor.translate(test_iter, step)
  File "[...]/PreSumm/src/models/predictor.py", line 157, in translate
    translations = self.from_batch(batch_data)
  File "[...]/PreSumm/src/models/predictor.py", line 110, in from_batch
    batch.tgt_str, batch.src))
ValueError: too many values to unpack (expected 5)

**Comment by Colanim** [comment]
I replaced :

https://github.com/nlpyang/PreSumm/blob/d5954c9890da487a40617ca77c75b02feff0d2eb/src/models/predictor.py#L103-L106

into :

```
preds, pred_score, gold_score, tgt_str, src =  translation_batch["predictions"], \
                                                       translation_batch["scores"], \
                                                       translation_batch["gold_score"], \
                                                       batch.tgt_str, batch.src
```

And it seems to work fine.

**Comment by nlpyang** [comment]
Yes, this is a bug and this has been fixed.
