### ISSUE TITLE
Training speed too slow with multiple-gpus

### ISSUE THREAD

**Issue by ShirleyHan6** [nlpyang/PreSumm#50]
Hi,

Has anyone tried to train with multiple-gpus?
I am using the same settings as in the README for BertAbs(with 4 gpus and batch size 140). However, right now for 200k steps to finish, it is estimated to take around 10 days.

(I am using pytorch==1.1)

**Comment by nlpyang** [comment]
As said in the paper, the model is trained on 4 gpus, and it took about 4 days.

**Comment by nlpyang** [comment]
@ShirleyHan6 I have double-checked, it took about 2 day to reach best performace on valid set

**Comment by zide05** [comment]
have you meet the problem that training procedure just "stop" with no log information and no error message at iteration of 83850?
