### ISSUE TITLE
memory use during validation step

### ISSUE THREAD

**Issue by antonysama** [nlpyang/PreSumm#55]
Please look at my script and the  link to the screenshot of memory usage, which was captured while I ran the script. Do you notice anything amiss in the script, which is causing memory use to be as low as 2 % ?  I need to find out why my validation step appears to running and running _ad infinitum_. . . 

`python ~/o3/PreSumm/src/train.py -task ext -mode validate -batch_size 300 -test_batch_size 50 -bert_data_path ~o3/PreSumm/bert_data/cnndm -log_file ~/o3/PreSumm/logs/ext_bert_cnndm -model_path ~o3/PreSumm/models/ -sep_optim true -use_interval true -visible_gpus -1 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path ~o3/PreSumm/logs/ext_bert_cnndm`

[https://github.com/antonysama/PreSumm/blob/master/Screenshot%20from%202019-10-13%2015-06-46.png](url) Platform is python 3.6 on linux 64 bit .

**Comment by nlpyang** [comment]
Batch size may be too small, here batch size means number of tokens in reference target. So batch_size=300 means 5 pairs. I usually set -batch_size 3000 -test_batch_size 500

**Comment by antonysama** [comment]
@nlpyang 
Thank you, that may help.
