### ISSUE TITLE
Beam search : Length normalization

### ISSUE THREAD

**Issue by Colanim** [nlpyang/PreSumm#58]
*In the beam search of your code, there is something I don't understand.*

You applied length normalization :

https://github.com/nlpyang/PreSumm/blob/b03f4853f461202f80ce905db732aac45470c542/src/models/predictor.py#L291-L294

As described in [Wu et al. 2016](https://arxiv.org/pdf/1609.08144.pdf) (Section 7). So far so good.

**But why do you un-normalize the scores afterward ?** i.e.

https://github.com/nlpyang/PreSumm/blob/b03f4853f461202f80ce905db732aac45470c542/src/models/predictor.py#L317

As far as I understand, if you un-normalize the scores, at the end when choosing the best beam, your scores are not length-normalized. Therefore the model will tend to choose shorter beams.

**Comment by nlpyang** [comment]
If you don't 'un-normalize' the probs, at the next time step, you will normalize it with length_penalty again. In the beam, we want to record real likelihood.

**Comment by Colanim** [comment]
Ha, it makes sense...

Thank you for your kind explanation 👍

**Comment by memeda** [comment]
Sorry to reopen. 
I think the code is somewhat confusing.
logically, the length-penalty don't affect the currently step sort order, because it  is a same scalar for every probs.
It only affect the saved and finished sequence scores.
I thought rewrite the code may be more clear...
