### ISSUE TITLE
Import trained model

### ISSUE THREAD

**Issue by candy9599** [nlpyang/PreSumm#59]
To load model, I need to know what kind of model it is.

`from modelfolder import Mymodel`

`model = Mymodel()`
`model = model.load_state_dict(torch.load('xxx.pt')['state_dict'])`

Sorry for being a newbie to pytorch, I don't know how to load your model (spoiled by keras). Do you have guides to use your trained model as well?
Thank you.

**Comment by candy9599** [comment]
Figured it out myself

**Comment by kurodenjiro** [comment]
How ? , can you help me ?

**Comment by CuthbertKarawa** [comment]
> Figured it out myself

how ??
