### ISSUE TITLE
Train.py in validate mode runs time.sleep(300)

### ISSUE THREAD

**Issue by poojavinod100** [nlpyang/PreSumm#62]
I left train.py running in validate mode for a long time(around an hour). Finally, I hit Ctrl+C, and this is what came up:
```
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    validate_ext(args, device_id)
  File "C:\Users\hp\Downloads\PreSumm-master\PreSumm-master\src\train_extractive.py", line 148, in validate_ext
    time.sleep(300)
```
Any ideas on what could be happening in the background?

(I downloaded and used the trained model(didn't do any of the training steps mentioned) and downloaded the pre-processed data and copied all .pt files into the bert-data folder. 

This was the cmd command I used to run train.py:

`python train.py -task ext -mode validate -batch_size 3000 -test_batch_size 500 -bert_data_path C:\Users\hp\Downloads\PreSumm-master\PreSumm-master\bert_data -log_file ../logs/val_abs_bert_cnndm -model_path C:\Users\hp\Downloads\bertext_cnndm_transformer -sep_optim true -use_interval true -visible_gpus 1 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path ../logs/ext_bert_cnndm`
)
Also, how do I give an input document I have, to the model and view the resulting output?(To verify the summarization)Please clarify. 

Thanks.

**Comment by germanenik** [comment]
@poojavinod100 hey did u figure this out? mine is also sleeping

**Comment by poojavinod100** [comment]
@germanenik I did not use train.py in validate mode thereafter. I used train.py in test and train modes only, and that worked for me.
