### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by CuthbertKarawa** [nlpyang/PreSumm#75]
I'm try to learning something from your code but i get some error during running process
![error](https://user-images.githubusercontent.com/16723586/68357825-901cb280-0151-11ea-9e3c-546987ca9d74.PNG)

**Comment by Colanim** [comment]
From where are you running your command ? It should be from `src` directory.

**Comment by CuthbertKarawa** [comment]
@Colanim i run through **colab notebook** i just modify some lines of code which does not affect anything

**Comment by Colanim** [comment]
Then what is the code in the cell of your notebook that led to this error ?

**Comment by CuthbertKarawa** [comment]
@Colanim what does test_from file looklike??

**Comment by CuthbertKarawa** [comment]
> Then what is the code in the cell of your notebook that led to this error ?

i manage to solve the error thank you

**Comment by CuthbertKarawa** [comment]
@Colanim @nlpyang  Error(s) in loading state_dict for AbsSummarizer:
