### ISSUE TITLE
Error in pyrouge.py

### ISSUE THREAD

**Issue by CuthbertKarawa** [nlpyang/PreSumm#76]
ModuleNotFoundError: No module named 'utils'
![error2](https://user-images.githubusercontent.com/16723586/68358132-8182cb00-0152-11ea-9381-7fe49a1c3ccb.PNG)

**Comment by Colanim** [comment]
From where are you running your command ? It should be from `src` directory.

**Comment by CuthbertKarawa** [comment]
I put everything together  and i use google colab i manage to train the model but i fail to validate and test it if possible i can share with you just give me your gmail account @Colanim

**Comment by CuthbertKarawa** [comment]
Error(s) in loading state_dict for AbsSummarizer()
@Colanim 
> /usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
>     775         if len(error_msgs) > 0:
>     776             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> --> 777                                self.__class__.__name__, "\n\t".join(error_msgs)))
>     778         return _IncompatibleKeys(missing_keys, unexpected_keys)
>     779 
> 
> RuntimeError: Error(s) in loading state_dict for AbsSummarizer:
> 	Missing key(s) in state_dict: "decoder.embeddings.weight", "decoder.pos_emb.pe", "decoder.transformer_layers.0.mask", "decoder.transformer_layers.0.self_attn.linear_keys.bias", "decoder.transformer_layers.0.self_attn.linear_keys.weight", "decoder.transformer_layers.0.self_attn.linear_values.bias", "decoder.transformer_layers.0.self_attn.linear_values.weight", "decoder.transformer_layers.0.self_attn.linear_query.bias", "decoder.transformer_layers.0.self_attn.linear_query.weight", "decoder.transformer_layers.0.self_attn.final_linear.bias", "decoder.transformer_layers.0.self_attn.final_linear.weight", "decoder.transformer_layers.0.context_attn.linear_keys.bias", "decoder.transformer_layers.0.context_attn.linear_keys.weight", "decoder.transformer_layers.0.context_attn.linear_values.bias", "decoder.transformer_layers.0.context_attn.linear_values.weight", "decoder.transformer_layers.0.context_attn.linear_query.bias", "decoder.transformer_layers.0.context_attn.linear_query.weight", "decoder.transformer_layers.0.context_attn.final_linear.bias", "decoder.transformer_layers.0.context_attn.final_linear.weight", "decoder.transformer_layers.0.feed_forward.w_1.bias", "decoder.transformer_layers.0.feed_forward.w_1.weight", "decoder.transformer_layers.0.feed_forward.w_2.bias", "decoder.transformer_layers.0.feed_forward.w_2.weight", "decoder.transformer_layers.0.feed_forward.layer_norm.bias", "decoder.transformer_layers.0.feed_forward.layer_norm.weight", "decoder.transformer_layers.0.layer_norm_1.bias", "decoder.transformer_layers.0.layer_norm_1.weight", "decoder.transformer_layers.0.layer_norm_2.bias", "decoder.transformer_layers.0.layer_norm_2.weight", "decoder.transformer_layers.1.mask", "decoder.transformer_layers.1.self_attn.linear_keys.bias", "decoder.transformer_layers.1.self_attn.linear_keys.weight", "decoder.transformer_layers.1.self_attn.linear_values.bias", "decoder.transformer_layers.1.self_attn.linear_values.weight", "decoder.transformer_layers.1.self_attn.linear_query.bias", "decoder.transformer_layers.1.self_attn.linear_query.weight", "decoder.transformer_layers.1.self_attn.final_linear.bias", "decoder.transformer_layers.1.self_attn.final_linear.weight", "decoder.transformer_layers.1.context_attn.linear_keys.bias", "decoder.transformer_layers.1.context_attn.linear_keys.weight", "decoder.transformer_layers.1.context_attn.linear_values.bias", "decoder.transformer_layers.1.context_attn.linear_values.weight", "decoder.transformer_layers.1.context_attn.linear_query.bias", "decoder.transformer_layers.1.context_attn.linear_query.weight", "decoder.transformer_layers.1.context_attn.final_linear.bias", "decoder.transformer_layers.1.context_attn.final_linear.weight", "decoder.transformer_layers.1.feed_forward.w_1.bias", "decoder.transformer_layers.1.feed_forward.w_1.weight", "decoder.transformer_layers.1.feed_forward.w_2.bias", "decoder.transformer_layers.1.feed_forward.w_2.weight", "decoder.transformer_layers.1.feed_forward.layer_norm.bias", "decoder.transformer_layers.1.feed_forward.layer_norm.weight", "decoder.transformer_layers.1.layer_norm_1.bias", "decoder.transformer_layers.1.layer_norm_1.weight", "decoder.transformer_layers.1.layer_norm_2.bias", "decoder.transformer_layers.1.layer_norm_2.weight", "decoder.transformer_layers.2.mask", "decoder.transformer_layers.2.self_attn.linear_keys.bias", "decoder.transformer_layers.2.self_attn.linear_keys.weight", "decoder.transformer_layers.2.self_attn.linear_values.bias", "decoder.transformer_layers.2.self_attn.linear_values.weight", "decoder.transformer_layers.2.self_attn.linear_query.bias", "decoder.transformer_layers.2.self_attn.linear_query.weight", "decoder.transformer_layers.2.self_attn.final_linear.bias", "decoder.transformer_layers.2.self_attn.final_linear.weight", "decoder.transformer_layers.2.context_attn.linear_keys.bias", "decoder.transformer_layers.2.context_attn.linear_keys.weight", "decoder.transformer_layers.2.context_attn.linear_values.bias", "decoder.transformer_layers.2.context_attn.linear_values.weight", "decoder.transformer_layers.2.context_attn.linear_query.bias", "decoder.transformer_layers.2.context_attn.linear_query.weight", "decoder.transformer_layers.2.context_attn.final_linear.bias", "decoder.transformer_layers.2.context_attn.final_linear.weight", "decoder.transformer_layers.2.feed_forward.w_1.bias", "decoder.transformer_layers.2.feed_forward.w_1.weight", "decoder.transformer_layers.2.feed_forward.w_2.bias", "decoder.transformer_layers.2.feed_forward.w_2.weight", "decoder.transformer_layers.2.feed_forward.layer_norm.bias", "decoder.transformer_layers.2.feed_forward.layer_norm.weight", "decoder.transformer_layers.2.layer_norm_1.bias", "decoder.transformer_layers.2.layer_norm_1.weight", "decoder.transformer_layers.2.layer_norm_2.bias", "decoder.transformer_layers.2.layer_norm_2.weight", "decoder.transformer_layers.3.mask", "decoder.transformer_layers.3.self_attn.linear_keys.bias", "decoder.transformer_layers.3.self_attn.linear_keys.weight", "decoder.transformer_layers.3.self_attn.linear_values.bias", "decoder.transformer_layers.3.self_attn.linear_values.weight", "decoder.transformer_layers.3.self_attn.linear_query.bias", "decoder.transformer_layers.3.self_attn.linear_query.weight", "decoder.transformer_layers.3.self_attn.final_linear.bias", "decoder.transformer_layers.3.self_attn.final_linear.weight", "decoder.transformer_layers.3.context_attn.linear_keys.bias", "decoder.transformer_layers.3.context_attn.linear_keys.weight", "decoder.transformer_layers.3.context_attn.linear_values.bias", "decoder.transformer_layers.3.context_attn.linear_values.weight", "decoder.transformer_layers.3.context_attn.linear_query.bias", "decoder.transformer_layers.3.context_attn.linear_query.weight", "decoder.transformer_layers.3.context_attn.final_linear.bias", "decoder.transformer_layers.3.context_attn.final_linear.weight", "decoder.transformer_layers.3.feed_forward.w_1.bias", "decoder.transformer_layers.3.feed_forward.w_1.weight", "decoder.transformer_layers.3.feed_forward.w_2.bias", "decoder.transformer_layers.3.feed_forward.w_2.weight", "decoder.transformer_layers.3.feed_forward.layer_norm.bias", "decoder.transformer_layers.3.feed_forward.layer_norm.weight", "decoder.transformer_layers.3.layer_norm_1.bias", "decoder.transformer_layers.3.layer_norm_1.weight", "decoder.transformer_layers.3.layer_norm_2.bias", "decoder.transformer_layers.3.layer_norm_2.weight", "decoder.transformer_layers.4.mask", "decoder.transformer_layers.4.self_attn.linear_keys.bias", "decoder.transformer_layers.4.self_attn.linear_keys.weight", "decoder.transformer_layers.4.self_attn.linear_values.bias", "decoder.transformer_layers.4.self_attn.linear_values.weight", "decoder.transformer_layers.4.self_attn.linear_query.bias", "decoder.transformer_layers.4.self_attn.linear_query.weight", "decoder.transformer_layers.4.self_attn.final_linear.bias", "decoder.transformer_layers.4.self_attn.final_linear.weight", "decoder.transformer_layers.4.context_attn.linear_keys.bias", "decoder.transformer_layers.4.context_attn.linear_keys.weight", "decoder.transformer_layers.4.context_attn.linear_values.bias", "decoder.transformer_layers.4.context_attn.linear_values.weight", "decoder.transformer_layers.4.context_attn.linear_query.bias", "decoder.transformer_layers.4.context_attn.linear_query.weight", "decoder.transformer_layers.4.context_attn.final_linear.bias", "decoder.transformer_layers.4.context_attn.final_linear.weight", "decoder.transformer_layers.4.feed_forward.w_1.bias", "decoder.transformer_layers.4.feed_forward.w_1.weight", "decoder.transformer_layers.4.feed_forward.w_2.bias", "decoder.transformer_layers.4.feed_forward.w_2.weight", "decoder.transformer_layers.4.feed_forward.layer_norm.bias", "decoder.transformer_layers.4.feed_forward.layer_norm.weight", "decoder.transformer_layers.4.layer_norm_1.bias", "decoder.transformer_layers.4.layer_norm_1.weight", "decoder.transformer_layers.4.layer_norm_2.bias", "decoder.transformer_layers.4.layer_norm_2.weight", "decoder.transformer_layers.5.mask", "decoder.transformer_layers.5.self_attn.linear_keys.bias", "decoder.transformer_layers.5.self_attn.linear_keys.weight", "decoder.transformer_layers.5.self_attn.linear_values.bias", "decoder.transformer_layers.5.self_attn.linear_values.weight", "decoder.transformer_layers.5.self_attn.linear_query.bias", "decoder.transformer_layers.5.self_attn.linear_query.weight", "decoder.transformer_layers.5.self_attn.final_linear.bias", "decoder.transformer_layers.5.self_attn.final_linear.weight", "decoder.transformer_layers.5.context_attn.linear_keys.bias", "decoder.transformer_layers.5.context_attn.linear_keys.weight", "decoder.transformer_layers.5.context_attn.linear_values.bias", "decoder.transformer_layers.5.context_attn.linear_values.weight", "decoder.transformer_layers.5.context_attn.linear_query.bias", "decoder.transformer_layers.5.context_attn.linear_query.weight", "decoder.transformer_layers.5.context_attn.final_linear.bias", "decoder.transformer_layers.5.context_attn.final_linear.weight", "decoder.transformer_layers.5.feed_forward.w_1.bias", "decoder.transformer_layers.5.feed_forward.w_1.weight", "decoder.transformer_layers.5.feed_forward.w_2.bias", "decoder.transformer_layers.5.feed_forward.w_2.weight", "decoder.transformer_layers.5.feed_forward.layer_norm.bias", "decoder.transformer_layers.5.feed_forward.layer_norm.weight", "decoder.transformer_layers.5.layer_norm_1.bias", "decoder.transformer_layers.5.layer_norm_1.weight", "decoder.transformer_layers.5.layer_norm_2.bias", "decoder.transformer_layers.5.layer_norm_2.weight", "decoder.layer_norm.bias", "decoder.layer_norm.weight", "generator.0.bias", "generator.0.weight". 
> 	Unexpected key(s) in state_dict: "ext_layer.pos_emb.pe", "ext_layer.transformer_inter.0.self_attn.linear_keys.weight", "ext_layer.transformer_inter.0.self_attn.linear_keys.bias", "ext_layer.transformer_inter.0.self_attn.linear_values.weight", "ext_layer.transformer_inter.0.self_attn.linear_values.bias", "ext_layer.transformer_inter.0.self_attn.linear_query.weight", "ext_layer.transformer_inter.0.self_attn.linear_query.bias", "ext_layer.transformer_inter.0.self_attn.final_linear.weight", "ext_layer.transformer_inter.0.self_attn.final_linear.bias", "ext_layer.transformer_inter.0.feed_forward.w_1.weight", "ext_layer.transformer_inter.0.feed_forward.w_1.bias", "ext_layer.transformer_inter.0.feed_forward.w_2.weight", "ext_layer.transformer_inter.0.feed_forward.w_2.bias", "ext_layer.transformer_inter.0.feed_forward.layer_norm.weight", "ext_layer.transformer_inter.0.feed_forward.layer_norm.bias", "ext_layer.transformer_inter.0.layer_norm.weight", "ext_layer.transformer_inter.0.layer_norm.bias", "ext_layer.transformer_inter.1.self_attn.linear_keys.weight", "ext_layer.transformer_inter.1.self_attn.linear_keys.bias", "ext_layer.transformer_inter.1.self_attn.linear_values.weight", "ext_layer.transformer_inter.1.self_attn.linear_values.bias", "ext_layer.transformer_inter.1.self_attn.linear_query.weight", "ext_layer.transformer_inter.1.self_attn.linear_query.bias", "ext_layer.transformer_inter.1.self_attn.final_linear.weight", "ext_layer.transformer_inter.1.self_attn.final_linear.bias", "ext_layer.transformer_inter.1.feed_forward.w_1.weight", "ext_layer.transformer_inter.1.feed_forward.w_1.bias", "ext_layer.transformer_inter.1.feed_forward.w_2.weight", "ext_layer.transformer_inter.1.feed_forward.w_2.bias", "ext_layer.transformer_inter.1.feed_forward.layer_norm.weight", "ext_layer.transformer_inter.1.feed_forward.layer_norm.bias", "ext_layer.transformer_inter.1.layer_norm.weight", "ext_layer.transformer_inter.1.layer_norm.bias", "ext_layer.layer_norm.weight", "ext_layer.layer_norm.bias", "ext_layer.wo.weight", "ext_layer.wo.bias".

**Comment by Colanim** [comment]
Can you share the command you used for running validation (or test) ?

It seems you are giving wrong checkpoint to load.

Which option are you using, `-test_all` or `-test_from` ?

**Comment by CuthbertKarawa** [comment]
> test_from

**Comment by CuthbertKarawa** [comment]
> Can you share the command you used for running validation (or test) ?
> 
> It seems you are giving wrong checkpoint to load.
> 
> Which option are you using, `-test_all` or `-test_from` ?
python train.py -task abs  -mode test-batch_size 3000 -test_batch_size 500 -bert_data_path / -log_file ../logs/val_abs_bert_cnndm 
-model_path models/ -sep_optim true -use_interval true -visible_gpus 1 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50
-test_from 'models/model_step_5.pt'
-result_path logs/abs_bert

**Comment by Colanim** [comment]
How did you get this checkpoint ? 

The name is weird, because if you follow the command in the README, checkpoints are supposed to be saved every 2k steps. So your checkpoint should have a name like : `model_step_2000.pt`, `model_step_4000.pt`, `model_step_6000.pt`, etc...

Did you modify the training command ?

**Comment by CuthbertKarawa** [comment]
> How did you get this checkpoint ?
> 
> The name is weird, because if you follow the command in the README, checkpoints are supposed to be saved every 2k steps. So your checkpoint should have a name like : `model_step_2000.pt`, `model_step_4000.pt`, `model_step_6000.pt`, etc...
> 
> Did you modify the training command ?

yes let me retraining it the try it again

**Comment by CuthbertKarawa** [comment]
@Colanim when i set torch==1.1.0  and set the visible gpu = 1  i get this error 

> RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/THCGeneral.cpp:50

and when i change to the new version of torch i get another error 

> subtraction, the `-` operator, with a bool tensor is not supported. if you are trying to invert a mask, use the `~` or `bitwise not()` operator instead.  
 how can  i solve this issue please

**Comment by Colanim** [comment]
This code base is written for Pytorch 1.1, so using new version of Pytorch will not work.

For your error about GPU, what happen when you run :

```
import torch

print(torch.cuda.is_available())
```

**Comment by CuthbertKarawa** [comment]
> This code base is written for Pytorch 1.1, so using new version of Pytorch will not work.
> 
> For your error about GPU, what happen when you run :
> 
> ```
> import torch
> 
> print(torch.cuda.is_available())
> ```

it return True

**Comment by CuthbertKarawa** [comment]
> > This code base is written for Pytorch 1.1, so using new version of Pytorch will not work.
> > For your error about GPU, what happen when you run :
> > ```
> > import torch
> > 
> > print(torch.cuda.is_available())
> > ```
> 
> it return True

i solve the issue thank you @Colanim

**Comment by CuthbertKarawa** [comment]
@Colanim  there another issue where the program is stack here it does not show anything during validation process
![Capture](https://user-images.githubusercontent.com/16723586/68818788-0c1e7980-06c1-11ea-9604-3273926bcf4a.PNG)

**Comment by Colanim** [comment]
How long did you wait ?

It takes quite some time for the program to predict every sample of the test data.

**Comment by CuthbertKarawa** [comment]
> How long did you wait ?
> 
> It takes quite some time for the program to predict every sample of the test data.

oohh okay and during validation how many time it should loop

**Comment by Colanim** [comment]
On validation, if you specified the `test_all` option, it will run each checkpoint on the validation data. 

Then it will keep the 5 best checkpoints and run these checkpoints on the test data (and compute rouge score).

There is 6 files for test and 6 files for validation.

If everything work correctly you should see from time to time :

>Loading test dataset from /home/me/PreSumm/your_data/cnndm.test.X.bert.pt, number of examples: 2000

**Comment by CuthbertKarawa** [comment]
> On validation, if you specified the `test_all` option, it will run each checkpoint on the validation data.
> 
> Then it will keep the 5 best checkpoints and run these checkpoints on the test data (and compute rouge score).
> 
> There is 6 files for test and 6 files for validation.
> 
> If everything work correctly you should see from time to time :
> 
> > Loading test dataset from /home/me/PreSumm/your_data/cnndm.test.X.bert.pt, number of examples: 2000

okay but i set test_all to be  true still take along time i decide to use test_from for validate

**Comment by CuthbertKarawa** [comment]
@Colanim  i get error during calculate rouge as you can see
![error](https://user-images.githubusercontent.com/16723586/68830620-194e5f00-06e7-11ea-870d-c63736edcd3e.PNG)

**Comment by CuthbertKarawa** [comment]
> @Colanim i get error during calculate rouge as you can see
> ![error](https://user-images.githubusercontent.com/16723586/68830620-194e5f00-06e7-11ea-870d-c63736edcd3e.PNG)

from file others/pyrouge.py

**Comment by Colanim** [comment]
There is not information for me to help you.

1. What is the code / command that lead to such error
2. Please paste full stack trace
3. You said it's from `others/pyrouge.py`, but it's not. At line 594 the code is different than the one showed in your image.

https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/others/pyrouge.py#L592-L596

---

Aside from this, if you have trouble with pyrouge I recommend you [this tutorial](https://stackoverflow.com/a/57686103/9494790) to install it correctly.

**Comment by CuthbertKarawa** [comment]
https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/others/pyrouge.py#L641

> There is not enough information for me to help you.
> 
> 1. What is the code / command that lead to such error ?
> 2. Please paste full stack trace
> 3. You said it's from `others/pyrouge.py`, but it's not. At line 594 the code is different than the one showed in your image.
> 
> https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/others/pyrouge.py#L592-L596
> 
> Aside from this, if you have trouble with pyrouge I recommend you [this tutorial](https://stackoverflow.com/a/57686103/9494790) to install it correctly.

https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/others/pyrouge.py#L641

**Comment by Colanim** [comment]
From where are you running your command ?

**Comment by CuthbertKarawa** [comment]
> From where are you running your command ?

[2019-11-14 07:06:47,828 INFO] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at /data/presum/temp/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
[2019-11-14 07:06:53,354 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.0.bert.pt, number of examples: 2001
[2019-11-14 07:06:54,606 INFO] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /data/presum/temp/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
[2019-11-14 07:10:51,836 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.1.bert.pt, number of examples: 2001
[2019-11-14 07:14:48,596 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.2.bert.pt, number of examples: 2001
[2019-11-14 07:18:45,022 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.3.bert.pt, number of examples: 2001
[2019-11-14 07:22:39,810 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.4.bert.pt, number of examples: 2001
[2019-11-14 07:26:33,557 INFO] Loading test dataset from /data/presum/bert_data_xsum_new/xsum.test.5.bert.pt, number of examples: 1329
[2019-11-14 07:29:11,328 INFO] Calculating Rouge
11334
11334
2019-11-14 07:29:12,257 [MainThread  ] [INFO ]  Writing summaries.
[2019-11-14 07:29:12,257 INFO] Writing summaries.
2019-11-14 07:29:12,262 [MainThread  ] [INFO ]  Processing summaries. Saving system files to /data/presum/temp/tmpfh8x1w0r/system and model files to /data/presum/temp/tmpfh8x1w0r/model.
[2019-11-14 07:29:12,262 INFO] Processing summaries. Saving system files to /data/presum/temp/tmpfh8x1w0r/system and model files to /data/presum/temp/tmpfh8x1w0r/model.
2019-11-14 07:29:12,264 [MainThread  ] [INFO ]  Processing files in /data/presum/temp/rouge-tmp-2019-11-14-07-29-11/candidate/.
[2019-11-14 07:29:12,264 INFO] Processing files in /data/presum/temp/rouge-tmp-2019-11-14-07-29-11/candidate/.
2019-11-14 07:29:13,530 [MainThread  ] [INFO ]  Saved processed files to /data/presum/temp/tmpfh8x1w0r/system.
[2019-11-14 07:29:13,530 INFO] Saved processed files to /data/presum/temp/tmpfh8x1w0r/system.
2019-11-14 07:29:13,534 [MainThread  ] [INFO ]  Processing files in /data/presum/temp/rouge-tmp-2019-11-14-07-29-11/reference/.
[2019-11-14 07:29:13,534 INFO] Processing files in /data/presum/temp/rouge-tmp-2019-11-14-07-29-11/reference/.
2019-11-14 07:29:14,569 [MainThread  ] [INFO ]  Saved processed files to /data/presum/temp/tmpfh8x1w0r/model.
[2019-11-14 07:29:14,569 INFO] Saved processed files to /data/presum/temp/tmpfh8x1w0r/model.
2019-11-14 07:29:14,744 [MainThread  ] [INFO ]  Written ROUGE configuration to /data/presum/temp/tmpo56qbqw4/rouge_conf.xml
[2019-11-14 07:29:14,744 INFO] Written ROUGE configuration to /data/presum/temp/tmpo56qbqw4/rouge_conf.xml
2019-11-14 07:29:14,747 [MainThread  ] [INFO ]  Running ROUGE with command /root/pyrouge/rouge/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl -e /root/pyrouge/rouge/tools/ROUGE-1.5.5/data -c 95 -m -r 1000 -n 2 -a /data/presum/temp/tmpo56qbqw4/rouge_conf.xml
[2019-11-14 07:29:14,747 INFO] Running ROUGE with command /root/pyrouge/rouge/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl -e /root/pyrouge/rouge/tools/ROUGE-1.5.5/data -c 95 -m -r 1000 -n 2 -a /data/presum/temp/tmpo56qbqw4/rouge_conf.xml
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-36-96e2672b9436> in <module>
    125             train_abs(args, device_id)
    126         elif (args.mode == 'validate'):
--> 127             validate_abs(args, device_id)
    128         elif (args.mode == 'lead'):
    129             baseline(args, cal_lead=True)

<ipython-input-25-29c0c453578b> in validate_abs(args, device_id)
    137         for xent, cp in xent_lst:
    138             step = int(cp.split('.')[-2].split('_')[-1])
--> 139             test_abs(args, device_id, cp, step)
    140     else:
    141         while (True):

<ipython-input-25-29c0c453578b> in test_abs(args, device_id, pt, step)
    223                'PAD': tokenizer.vocab['[PAD]'], 'EOQ': tokenizer.vocab['[unused2]']}
    224     predictor = build_predictor(args, tokenizer, symbols, model, logger)
--> 225     predictor.translate(test_iter, step)
    226 
    227 

<ipython-input-19-d56ce64a2577> in translate(self, data_iter, step, attn_debug)
    183 
    184         if (step != -1):
--> 185             rouges = self._report_rouge(gold_path, can_path)
    186             self.logger.info('Rouges at step %d \n%s' % (step, rouge_results_to_str(rouges)))
    187             if self.tensorboard_writer is not None:

<ipython-input-19-d56ce64a2577> in _report_rouge(self, gold_path, can_path)
    192     def _report_rouge(self, gold_path, can_path):
    193         self.logger.info("Calculating Rouge")
--> 194         results_dict = test_rouge(self.args.temp_dir, can_path, gold_path)
    195         return results_dict
    196 

<ipython-input-35-66b57e6fe10c> in test_rouge(temp_dir, cand, ref)
     82         r.model_filename_pattern = 'ref.#ID#.txt'
     83         r.system_filename_pattern = r'cand.(\d+).txt'
---> 84         rouge_results = r.convert_and_evaluate()
     85         print(rouge_results)
     86         results_dict = r.output_to_dict(rouge_results)

<ipython-input-34-2e245af5f246> in convert_and_evaluate(self, system_id, split_sentences, rouge_args)
    356             self.split_sentences()
    357         self.__write_summaries()
--> 358         rouge_output = self.evaluate(system_id, rouge_args)
    359         return rouge_output
    360 

<ipython-input-34-2e245af5f246> in evaluate(self, system_id, rouge_args)
    335         self.log.info(
    336             "Running ROUGE with command {}".format(" ".join(command)))
--> 337         rouge_output = check_output(command).decode("UTF-8")
    338         return rouge_output
    339 

/opt/conda/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    354 
    355     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 356                **kwargs).stdout
    357 
    358 

/opt/conda/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    436         if check and retcode:
    437             raise CalledProcessError(retcode, process.args,
--> 438                                      output=stdout, stderr=stderr)
    439     return CompletedProcess(process.args, retcode, stdout, stderr)
    440 

CalledProcessError: Command '['/root/pyrouge/rouge/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/root/pyrouge/rouge/tools/ROUGE-1.5.5/data', '-c', '95', '-m', '-r', '1000', '-n', '2', '-a', '/data/presum/temp/tmpo56qbqw4/rouge_conf.xml']' returned non-zero exit status 2.

**Comment by Colanim** [comment]
Can you successfully run the tests of pyrouge ?

`python -m pyrouge.test`

What is the output of this command ?

**Comment by CuthbertKarawa** [comment]
> python -m pyrouge.test

![error](https://user-images.githubusercontent.com/16723586/68836456-5f122400-06f5-11ea-9bfa-8a0319ce889f.PNG)

**Comment by CuthbertKarawa** [comment]
i follow all the procedure in the [Tutorial](https://stackoverflow.com/questions/45894212/installing-pyrouge-gets-error-in-ubuntu/57686103#57686103)

**Comment by Colanim** [comment]
So, we know the problem : your pyrouge installation is wrong.

---

From the error message in the pyrouge's tests, it seems you skipped step 3 of the tutorial : 

`pyrouge_set_rouge_path ~/pyrouge/rouge/tools/ROUGE-1.5.5/`

You have to replace the ROUGE path with your path where the official rouge is installed, and it should be an absolute path.

**Comment by CuthbertKarawa** [comment]
i repeat all the steps again 
![Capture](https://user-images.githubusercontent.com/16723586/68837704-1ad45300-06f8-11ea-9fb9-2d150ba13d49.PNG)
and skip step 4 and 5 but still get the error

**Comment by Colanim** [comment]
Is it exactly the same error ?

If Yes, I'm sorry but I can't help. It's a pyrouge error. I can open an issue in their github repository.

**Comment by congdoanit98** [comment]
> ModuleNotFoundError: No module named 'utils'
> ![error2](https://user-images.githubusercontent.com/16723586/68358132-8182cb00-0152-11ea-9381-7fe49a1c3ccb.PNG)

I also got this issue. Have you solved the problem yet?
