### ISSUE TITLE
Regarding training on custom data

### ISSUE THREAD

**Issue by ranjeetds** [nlpyang/PreSumm#79]
While training model on custom data, where should we put summaries corresponding to the text articles? As in RAW_DATA we put stories that is articles.

**Comment by CuthbertKarawa** [comment]
@ranjeetds i thing you should follow the preprocessing steps in [README.dm](https://github.com/nlpyang/PreSumm#option-2-process-the-data-yourself)

**Comment by ranjeetds** [comment]
@CuthbertKarawa Got carried away by thoughts. Sorry and thanks

**Comment by Weilin37** [comment]
> @CuthbertKarawa Got carried away by thoughts. Sorry and thanks



> While training model on custom data, where should we put summaries corresponding to the text articles? As in RAW_DATA we put stories that is articles.

sorry but what was the solution? I am having some confusion on this as well

**Comment by Vinothsuku** [comment]
@ranjeetds could you pls let us know the solution (where to place the summaries)? couldn't figure it out yet:(

**Comment by ranjeetds** [comment]
@Vinothsuku  @Weilin37 Confusion happens. Go to >data>unfinished folder. You will have training and validation dataset.  Your training stories will go inside the file titles "train.article.txt" validation stories will go inside "valid.article.filter.txt". Correspondingly your summaries for training will go inside a file named "train.title.txt" and validation summaries will go in "valid.title.filter.txt".

You need the above names as make_data_files.py script is pointing to these files. you can always edit this make_data_file.py file and on line 112, 113 change names of these files in order to avoid any confusion.

Hope this helps.

Thanks,
Ranjeet Dhumal

**Comment by ranjeetds** [comment]
@Weilin37 @Vinothsuku  In ```raw_path``` folder inside each story ```@highlight``` is summary separator so add your summaries at the end of the story file starting with ```@hightlight``` line as a separator.

If you want summaries to be read from separate files, You can find this separator mentioned in the ```data_builder.py``` file and change that part of the code.

**Comment by Vinothsuku** [comment]
Thanks

**Comment by Vinothsuku** [comment]
@ranjeetds Could you pls shed some light on training on custom data like how many articles you used? Results were good? Was it trained from scratch or you did transfer learning? If transfer learning would be glad to hear some directions to get started...Thanks

**Comment by GraphGrailAi** [comment]
@ranjeetds  hi, i do not see any `@highlight` word in https://github.com/nlpyang/PreSumm/blob/dev/raw_data/temp.raw_src

**Comment by AyeshaSarwar** [comment]
> @Weilin37 @Vinothsuku In `raw_data` folder inside each story `@highlight` is summary separator so add your summaries at the end of the story file starting with `@hightlight` line as a separator.
> 
> If you want summaries to be read from separate files, You can find this separator mentioned in the `data_builder.py` file and change that part of the code.

You mean @highlight followed by one summary which could be multiple lines as well. or each line of summary must be separated by @highlight??

**Comment by ranjeetds** [comment]
@AyeshaSarwar Article and summary should be seperated by **@highlight** you can have any number of **@highlight** in the summary as all the statements after **@hightlight** are considered to be summary.  

@GraphGrailAi  please go through last section of ```data_builder.py``` file from dev branch you will understand why it is like that.

**Comment by AyeshaSarwar** [comment]
Thanks a lot
I go and check it
Yup I have separated them by @highlight
You mean to say it does not matter if I put @highlight after every line in the summary. Actually I put @highlight for every sentence in the summary. So a little confused.

**Comment by ranjeetds** [comment]
There is nothing wrong in putting it before every summary line. You can also put it only once after article and before summary.
