### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by CuthbertKarawa** [nlpyang/PreSumm#81]
what  should i pass in this line of code  
https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/post_stats.py#L83

**Comment by Colanim** [comment]
`train` or `validate` or `test`

**Comment by CuthbertKarawa** [comment]
> `train` or `validate` or `test`


![Capture](https://user-images.githubusercontent.com/16723586/69019615-4ef78e80-09ec-11ea-9224-b82fa0240d4d.PNG)

**Comment by CuthbertKarawa** [comment]
> > `train` or `validate` or `test`
> 
> ![Capture](https://user-images.githubusercontent.com/16723586/69019615-4ef78e80-09ec-11ea-9224-b82fa0240d4d.PNG)

I get error in this line 
https://github.com/nlpyang/PreSumm/blob/ba17e95de8cde9d5ddaeeba01df7cace584511b2/src/post_stats.py#L88

**Comment by Colanim** [comment]
Ha, it's for `post_stats.py` ?

I don't know, I never run this file. Input from the author would be welcome.

From reading the source code, I think the only possible argument would be `cal_repeat`.

**Comment by CuthbertKarawa** [comment]
> cal_repeat

Thank you brother
