### ISSUE TITLE
Two spaces generated rather than separator token

### ISSUE THREAD

**Issue by CreateRandom** [nlpyang/PreSumm#88]
After analyzing the test set outputs of the model, I found that in some places, two spaces are generated. It appears that this always indicates a sentence boundary:

> <q>but no one has come forward with ideas for which streets should fill the brown sections of the board , which cost $ 60 in monopoly **money  exeter** has outdone all previous cities to get their own board - including oxford , cambridge and york - in the posh stakes , with no suggestions for the lower end

> <q>he will be sentenced in sydney 's local court , where the maximum jail term is two years , rather than the district **court  people** could face up to 10 years for that offence

> <q>she says cruelty provides a lens into the worst of the worst , and we identify certain victims as especially **worthy  ghitis** : for 2,500 years , we have proclaimed that all human beings are equally valuable

(Three examples, the double spaces surrounded by bold face)

The test set output contains a total of 326 double spaces. Has anyone else encountered this problem and can offer an explanation of what is going on?

**Comment by nlpyang** [comment]
This might be a post-processing problem, as we use a special token <q> for indicating the sentence boundaries, and we replace this token with white space, this might lead to the double spaces.
