### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by 440181N-440H4N4N** [nlpyang/PreSumm#9]
Hi, I tried to run the code in jupyter notebook, but couldn't get past the 'import' section. It keeps telling me the issue mentioned. How do I solve this problem?
Please respond.

**Comment by Colanim** [comment]
You should run the code from `PreSumm/src`, not `PreSumm`

**Comment by 440181N-440H4N4N** [comment]
Thanks. I'm new to this coding stuff, that's why I'm facing these problems.
:)

**Comment by 440181N-440H4N4N** [comment]
That I did. 
I run the code from ...\PreSumm-master\PreSumm-master\src\train_abstractive.py

**Comment by Colanim** [comment]
Try adding `...\PreSumm-master\src` (absolute path) to the Path.
