### ISSUE TITLE
ABS baseline evaluation

### ISSUE THREAD

**Issue by zide05** [nlpyang/PreSumm#91]
i train the abs baseline model using command:
python train.py -task abs -mode train -bert_data_path ../bert_data/bert_data_cnndm_final/cnndm -dec_dropout 0.1 -model_path ../models/cnndm_baseline_abs -lr 0.05 -save_checkpoint_steps 2000 -batch_size 300 -train_steps 200000 -report_every 50 -accum_count 5 -log_file ../logs/cnndm_baseline -seed 777 -sep_optim false -use_bert_emb true -use_interval true -warmup_steps 8000  -visible_gpus 3,5 -max_pos 512 -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 -dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 -encoder baseline

and use 
python train.py -task abs -mode test -batch_size 3000 -test_batch_size 500 -bert_data_path ../bert_data/bert_data_cnndm_final/cnndm -log_file ../logs/baseline_abs_bert_cnndm_result/val_baseline_abs_bert_model_cnndm_data_cnndm.200000 -model_path ../models/cnndm_abs -test_from ../models/cnndm_abs/model_step_200000.pt -sep_optim False -use_interval true -visible_gpus 0 -max_pos 512 -max_length 100 -alpha 0.9 -min_length 20 -result_path ../logs/baseline_abs_bert_cnndm_result/baseline_abs_bert_model_cnndm_data_cnndm

to test the result, but the performance is really poor : only ROUGE-F(1/2/3/l): 9.30/0.56/8.72 on step 200000, why could this happened ?

**Comment by nlpyang** [comment]
Please read the instructions and,
1. Use 4 gpus
2. Do validation instead of directly using a ckpt (for early stop)
3. Set -max_length 200 -alpha 0.95 -min_length 50  for CNNDM

**Comment by zide05** [comment]
I got this, thank you very much. 
Another question is : do i have to sepecify -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 -dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 -encoder baseline when testing same as whart training stage do?
