### ISSUE TITLE
Can't reproduce ABS baseline

### ISSUE THREAD

**Issue by zide05** [nlpyang/PreSumm#94]
**I run the code:**

python train.py -mode train -accum_count 5 -batch_size 300 -bert_data_path ../bert_data/bert_data_cnndm_final/cnndm -dec_dropout 0.1 -log_file ../logs/cnndm_baseline -lr 0.05 -model_path ../models/cnndm_baseline_abs -save_checkpoint_steps 2000 -seed 777 -sep_optim false -train_steps 200000 -use_bert_emb true -use_interval true -warmup_steps 8000  -visible_gpus 5 -max_pos 512 -report_every 50 -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 -dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 -encoder baseline -task abs

**to train my abs baseline mode (just replace the data path , model path and log path compare the commad in readme)**

**and use the code:**

python train.py -task abs -mode test -batch_size 3000 -test_batch_size 500 -bert_data_path ../bert_data/bert_data_cnndm_final/cnndm -log_file ../logs/baseline_abs_bert_cnndm_result/val_baseline_abs_bert_model_cnndm_data_cnndm.88000 -model_path ../models/cnndm_baseline_abs -test_from ../models/cnndm_baseline_abs/model_step_88000.pt -sep_optim False -use_interval true -visible_gpus 7 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path ../logs/baseline_abs_bert_cnndm_result/baseline_abs_bert_model_cnndm_data_cnndm -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 -dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 -encoder baseline -seed 777 -use_bert_emb true

**to test model_step_88000.pt.**
**" -enc_hidden_size 512  -enc_layers 6 -enc_ff_size 2048 -enc_dropout 0.1 -dec_layers 6 -dec_hidden_size 512 -dec_ff_size 2048 -encoder baseline -seed 777 -use_bert_emb true" might be 
unnecessary when test, i just add them here incase they are useful.**
**but got the result : (even though i test at step 88000, it should not be so bad, cause it has already trained nearly half of 200000 steps)**
>> ROUGE-F(1/2/3/l): 7.19/0.14/6.85
ROUGE-R(1/2/3/l): 7.13/0.14/6.79

**I check the baseline_abs_bert_model_cnndm_data_cnndm.88000.candidate file which store the predicted summary and find the result like:**

![image](https://user-images.githubusercontent.com/24726796/69835874-a369fc00-127f-11ea-96c5-82d86309b313.png)

**the same result is repeating, how could this happened ?**

**Comment by shashankMadan-designEsthetics** [comment]
Hi i am curious on how did you get the back the raw summaries?
I ran the following command
` python train.py -task abs -mode test -test_from ../models/cnndm_baseline_best.pt -batch_size 3000 -test_batch_size 500 -bert_data_path BERT_DATA_PATH -log_file ../logs/val_abs_bert_cnndm -model_path ../models -sep_optim true -use_interval true -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path ../logs/abs_bert_cnndm `
What am i missing?

**Comment by txAnnie** [comment]
@zide05 Have you solved the problem?

**Comment by WSChange** [comment]
How do you save your best model?
